test

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -37,9 +37,9 @@ jobs:
       - name: Testing
         run: docker compose exec -it dash pytest -v
 
-      - name: Build Docker image
-        run: |
-          docker buildx build -t kaungnyo/a3-dash:latest -f dash.Dockerfile .
+      # - name: Build Docker image
+      #   run: |
+      #     docker buildx build -t kaungnyo/a3-dash:latest -f dash.Dockerfile .
       # If the testing pass, upload the image
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -47,25 +47,25 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Push Docker image to Docker Hub
-        run: docker push kaungnyo/a3-dash:latest
+      # - name: Push Docker image to Docker Hub
+      #   run: docker push kaungnyo/a3-dash:latest
       # - name: Set up Docker Buildx
       #   uses: docker/setup-buildx-action@v3
-      # - name: Docker meta
-      #   id: meta
-      #   uses: docker/metadata-action@v5
-      #   with:
-      #     # Your image name
-      #     images: kaungnyo/a3-dash
-      #     tags: type=semver,pattern={{raw}}
-      #     # tags: latest
-      # - name: Build and push
-      #   uses: docker/build-push-action@v5
-      #   with:
-      #     context: .
-      #     file: dash.Dockerfile
-      #     push: true
-      #     tags: ${{ steps.meta.outputs.tags }}
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          # Your image name
+          images: kaungnyo/a3-dash
+          tags: type=semver,pattern={{raw}}
+          # tags: latest
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: dash.Dockerfile
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
           # tags: latest
   # deploy:
   #   environment: Production
@@ -129,17 +129,17 @@ jobs:
             echo "Listing files:"
             ls -al
 
-            # tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml down
-            # tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml up -d
+            tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml down
+            tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml up -d
 
-            echo "Pulling the latest Docker image..."
-            docker pull kaungnyo/a3-dash:latest || { echo "Docker not found. Exiting."; exit 1; }
+            # echo "Pulling the latest Docker image..."
+            # docker pull kaungnyo/a3-dash:latest || { echo "Docker not found. Exiting."; exit 1; }
             
-            echo "Stopping existing containers..."
-            docker compose -f st125066/docker-compose.yaml down || true 
+            # echo "Stopping existing containers..."
+            # docker compose -f st125066/docker-compose.yaml down || true 
             
-            echo "Starting containers with Docker Compose..."
-            docker compose -f st125066/docker-compose.yaml up -d 
+            # echo "Starting containers with Docker Compose..."
+            # docker compose -f st125066/docker-compose.yaml up -d 
 
             exit  # End the SSH session
           EOF
