test

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -36,29 +36,36 @@ jobs:
       # Execute pytest
       - name: Testing
         run: docker compose exec -it dash pytest -v
+
+      - name: Build Docker image
+        run: |
+          docker build -t kaungnyo/a3-dash:latest 
       # If the testing pass, upload the image
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Push Docker image to Docker Hub
+        run: docker push kaungnyo/a3-dash:latest
       # - name: Set up Docker Buildx
       #   uses: docker/setup-buildx-action@v3
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          # Your image name
-          images: kaungnyo/a3-dash
-          tags: type=semver,pattern={{raw}}
-          # tags: latest
-      - name: Build and push
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: dash.Dockerfile
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
+      # - name: Docker meta
+      #   id: meta
+      #   uses: docker/metadata-action@v5
+      #   with:
+      #     # Your image name
+      #     images: kaungnyo/a3-dash
+      #     tags: type=semver,pattern={{raw}}
+      #     # tags: latest
+      # - name: Build and push
+      #   uses: docker/build-push-action@v5
+      #   with:
+      #     context: .
+      #     file: dash.Dockerfile
+      #     push: true
+      #     tags: ${{ steps.meta.outputs.tags }}
           # tags: latest
   # deploy:
   #   environment: Production
@@ -124,8 +131,15 @@ jobs:
 
             # tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml down
             # tag=${{ github.ref_name }} docker compose -f st125066/docker-compose.yaml up -d
-            tag=v1.0.30 docker compose -f st125066/docker-compose.yaml down
-            tag=v1.0.30 docker compose -f st125066/docker-compose.yaml up -d
+
+            echo "Pulling the latest Docker image..."
+            docker pull kaungnyo/a3-dash:latest || { echo "Docker not found. Exiting."; exit 1; }
+            
+            echo "Stopping existing containers..."
+            docker compose down || true 
+            
+            echo "Starting containers with Docker Compose..."
+            docker compose up -d 
 
             exit  # End the SSH session
           EOF
